openai_api_key: ""
vad_mode: 1
kafka_broker: "localhost:9092"
db_url: "sqlite:///lia_context.db"
ws_host: "0.0.0.0"
ws_port: 8765
auth_token: "token123"
languages:
  - pt
  - en
  - es
mqtt_broker: "localhost"
vosk_model_path: "models/vosk-model-small"
whisper_model: "small"
rasa_url: "http://localhost:5005/model/parse"
pv_access_key: "/Wq+L2LAOBqKb0yTQ1o5XSil9CcK7fq/8Z5mks64jRo/6CNoBj+QzA=="
pv_library_path: ""
pv_model_path: ""
pv_keyword_path: ""
pv_sensitivity: 0.5
audio_input_device: null
